default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_original

development:
  <<: *default

production:
  <<: *default
  host: dpg-cq917b5ds78s7396u9pg-a
  database: s_original_2ckj
  username: s_original_2ckj_user
  password: dHXyMLBipR7TjtqweQrIIz2ViSv8lvmc
