default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_original

development:
  <<: *default

production:
  <<: *default
  host: dpg-clhoa26g1b2c73ag919g-a
  database: s_original_ime8
  username: s_original_ime8_user
  password: UgtVaPAkDdvc9MbsoQ5IImzgnvRD5m3d
