default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_todo

development:
  <<: *default

production:
  <<: *default
  host: dpg-clhom3fjc5ks73endrb0-a
  database: s_todo
  username: s_todo_user
  password: XYKyPcDw9Yz3JSj9ZeGd9AHCMXh9REof
